// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
 
export const GET_COVIDS_LIST = "GET_COVIDS_LIST"
export const GET_COVID_INDO = "GET_COVID_INDO"
export const GET_COVID_POSITIF = "GET_COVID_POSITIF"
export const GET_COVID_SEMBUH = "GET_COVID_SEMBUH"